version: '3'
services:
#mssql docker   
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: "rabbitmq"
    labels:
        NAME: "rabbitmq"
    restart: unless-stopped
    environment:
        - RABBITMQ_DEFAULT_USER=${_rabbitMqUser}
        - RABBITMQ_DEFAULT_PASS=${_rabbitMqPassword}
    ports:
        - "15672:15672"
        - "5672:5672"
    expose:
        - 5672
        - 15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
        - elibrarynet2024
   
  elibrary-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    user: root
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${_saPassword}
        - MSSQL_PID=Developer
    ports:
        - 1401:1433
    networks:
        - elibrarynet2024
    
  
  elibrary-api:
      restart: unless-stopped
      build:
        context: .
      environment:
        - ConnectionStrings:eLibraryConnection=Server=elibrary-sql,1433;Database=210046;User=sa;Password=${_saPassword};ConnectRetryCount=0;TrustServerCertificate=True
        - ASPNETCORE_ENVIRONMENT=Development
        - _fromAddress=${_fromAddress}
        - _password=${_password}
        - _host=${_host}
        - _enableSSL=${_enableSSL}
        - _displayName=${_displayName}
        - _timeout=${_timeout}
        - _port=${_port}
        - _rabbitMqHost=${_rabbitMqHost}
        - _rabbitMqUser=${_rabbitMqUser}
        - _rabbitMqPassword=${_rabbitMqPassword}
        - _rabbitMqPort=${_rabbitMqPort}
        - _saPassword=${_saPassword}
      ports:
        - 5023:5023
      networks:
        - elibrarynet2024
      links:
        - elibrary-sql
      depends_on:
        - elibrary-sql
        - rabbitmq

  elibrary-console:
    restart: on-failure
    build:
      context: ./eLibrary.Subscriber
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq      
    environment:
        - _fromAddress=${_fromAddress}
        - _password=${_password}
        - _host=${_host}
        - _enableSSL=${_enableSSL}
        - _displayName=${_displayName}
        - _timeout=${_timeout}
        - _port=${_port}
        - _rabbitMqHost=${_rabbitMqHost}
        - _rabbitMqUser=${_rabbitMqUser}
        - _rabbitMqPassword=${_rabbitMqPassword}
        - _rabbitMqPort=${_rabbitMqPort}
    networks:
      - elibrarynet2024


networks:
  elibrarynet2024:
    driver: bridge      